// Auto-generated by build-ai-courses.py — do not edit manually.
export const AI_BEGINNERS_PHASES = [
  {
    "id": 0,
    "name": "Course Setup",
    "desc": "Setup your development environment.",
    "status": "complete",
    "lessons": [
      {
        "name": "Course Setup",
        "status": "complete",
        "type": "Build",
        "lang": "Python, Bash",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/0-course-setup/setup.md",
        "summary": "Setting up your development environment with Python, VS Code, and standard tools.",
        "keywords": "Path: 00-setup.md",
        "path": "00-setup.md"
      }
    ]
  },
  {
    "id": 1,
    "name": "Introduction to AI",
    "desc": "Fundamental concepts, course setup, and the history of AI.",
    "status": "complete",
    "lessons": [
      {
        "name": "Introduction and History of AI",
        "status": "complete",
        "type": "Learn",
        "lang": "\u2014",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/1-Intro/README.md",
        "summary": "Overview of the course, what is AI, and the history of Artificial Intelligence.",
        "keywords": "Path: 01-intro.md",
        "path": "01-intro.md"
      }
    ]
  },
  {
    "id": 2,
    "name": "Symbolic AI",
    "desc": "Knowledge representation, search algorithms, and ontologies.",
    "status": "complete",
    "lessons": [
      {
        "name": "Knowledge Representation and Expert Systems",
        "status": "complete",
        "type": "Learn",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/2-Symbolic/README.md",
        "summary": "Learn about production systems, semantic webs, ontologies, and logical reasoning.",
        "keywords": "Path: 02-symbolic.md",
        "path": "02-symbolic.md"
      }
    ]
  },
  {
    "id": 3,
    "name": "Introduction to Neural Networks",
    "desc": "From simple perceptrons to deep networks and modern frameworks.",
    "status": "complete",
    "lessons": [
      {
        "name": "Perceptron",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/3-NeuralNetworks/03-Perceptron/README.md",
        "summary": "Learn about single-layer perceptrons, backpropagation, and multi-layered networks.",
        "keywords": "Path: 03-perceptron.md",
        "path": "03-perceptron.md"
      },
      {
        "name": "Multi-Layered Perceptron and Creating our own Framework",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/3-NeuralNetworks/04-OwnFramework/README.md",
        "summary": "Understand neural networks by building a backpropagation framework from scratch.",
        "keywords": "Path: 04-ownframework.md",
        "path": "04-ownframework.md"
      },
      {
        "name": "Intro to Frameworks (PyTorch/TensorFlow) and Overfitting",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/3-NeuralNetworks/05-Frameworks/README.md",
        "summary": "Introduction to PyTorch and TensorFlow for deep neural networks.",
        "keywords": "Path: 05-frameworks.md",
        "path": "05-frameworks.md"
      }
    ]
  },
  {
    "id": 4,
    "name": "Computer Vision",
    "desc": "Processing images, CNNs, generative models, and object segmentation.",
    "status": "complete",
    "lessons": [
      {
        "name": "Intro to Computer Vision. OpenCV",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/4-ComputerVision/06-IntroCV/README.md",
        "summary": "Traditional computer vision techniques, image manipulation, and OpenCV.",
        "keywords": "Path: 06-introcv.md",
        "path": "06-introcv.md"
      },
      {
        "name": "Convolutional Neural Networks & CNN Architectures",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/4-ComputerVision/07-ConvNets/README.md",
        "summary": "Understanding convolutions, pooling, kernels, and standard CNN architectures.",
        "keywords": "Path: 07-convnets.md",
        "path": "07-convnets.md"
      },
      {
        "name": "Pre-trained Networks and Transfer Learning and Training Tricks",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/4-ComputerVision/08-TransferLearning/README.md",
        "summary": "Using pre-trained models (ResNet, VGG) to classify images with small datasets.",
        "keywords": "Path: 08-transferlearning.md",
        "path": "08-transferlearning.md"
      },
      {
        "name": "Autoencoders and VAEs",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/4-ComputerVision/09-Autoencoders/README.md",
        "summary": "Dimensionality reduction, latent spaces, denoising, and autoencoders.",
        "keywords": "Path: 09-autoencoders.md",
        "path": "09-autoencoders.md"
      },
      {
        "name": "Generative Adversarial Networks & Artistic Style Transfer",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/4-ComputerVision/10-GANs/README.md",
        "summary": "Introduction to generative AI, training generator and discriminator networks.",
        "keywords": "Path: 10-gans.md",
        "path": "10-gans.md"
      },
      {
        "name": "Object Detection",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/4-ComputerVision/11-ObjectDetection/README.md",
        "summary": "Predicting coordinates of object bounding boxes using YOLO and SSD architectures.",
        "keywords": "Path: 11-objectdetection.md",
        "path": "11-objectdetection.md"
      },
      {
        "name": "Semantic Segmentation. U-Net",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/4-ComputerVision/12-Segmentation/README.md",
        "summary": "Pixel-level classification, segmentation techniques, and the U-Net architecture.",
        "keywords": "Path: 12-segmentation.md",
        "path": "12-segmentation.md"
      }
    ]
  },
  {
    "id": 5,
    "name": "Natural Language Processing",
    "desc": "Text preprocessing, embeddings, RNNs, Transformers, and LLMs.",
    "status": "complete",
    "lessons": [
      {
        "name": "Text Representation. Bow/TF-IDF",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/5-NLP/13-TextRep/README.md",
        "summary": "Bag-of-Words, TF-IDF representations, and classical text classification.",
        "keywords": "Path: 13-textrep.md",
        "path": "13-textrep.md"
      },
      {
        "name": "Semantic word embeddings. Word2Vec and GloVe",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/5-NLP/14-Embeddings/README.md",
        "summary": "Continuous word representations (Word2Vec, GloVe) and embedding layers.",
        "keywords": "Path: 14-embeddings.md",
        "path": "14-embeddings.md"
      },
      {
        "name": "Language Modeling. Training your own embeddings",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/5-NLP/15-LanguageModeling/README.md",
        "summary": "Generating text using n-grams and neural network language models.",
        "keywords": "Path: 15-languagemodeling.md",
        "path": "15-languagemodeling.md"
      },
      {
        "name": "Recurrent Neural Networks",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/5-NLP/16-RNN/README.md",
        "summary": "Sequence modeling using LSTM and GRU networks for text processing.",
        "keywords": "Path: 16-rnn.md",
        "path": "16-rnn.md"
      },
      {
        "name": "Generative Recurrent Networks",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/5-NLP/17-GenerativeNetworks/README.md",
        "summary": "Encoder-decoder models, sequence-to-sequence learning, and machine translation.",
        "keywords": "Path: 17-generativenlp.md",
        "path": "17-generativenlp.md"
      },
      {
        "name": "Transformers. BERT.",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/5-NLP/18-Transformers/README.md",
        "summary": "Self-attention mechanisms, multi-head attention, and Transformer layers.",
        "keywords": "Path: 18-transformers.md",
        "path": "18-transformers.md"
      },
      {
        "name": "Named Entity Recognition",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/5-NLP/19-NER/README.md",
        "summary": "Identifying and classifying specific entities (e.g. people, places) in text.",
        "keywords": "Path: 19-ner.md",
        "path": "19-ner.md"
      },
      {
        "name": "Large Language Models, Prompt Programming and Few-Shot Tasks",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/5-NLP/20-LangModels/README.md",
        "summary": "BERT, GPT-2/3, prompt engineering, and modern Large Language Models.",
        "keywords": "Path: 20-langmodels.md",
        "path": "20-langmodels.md"
      }
    ]
  },
  {
    "id": 6,
    "name": "Other AI Techniques",
    "desc": "Genetic algorithms, Reinforcement Learning, and Multi-Agent systems.",
    "status": "complete",
    "lessons": [
      {
        "name": "Genetic Algorithms",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/6-Other/21-GeneticAlgorithms/README.md",
        "summary": "Evolutionary optimization, selection, crossover, and mutation mechanisms.",
        "keywords": "Path: 21-geneticalgorithms.md",
        "path": "21-geneticalgorithms.md"
      },
      {
        "name": "Deep Reinforcement Learning",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/6-Other/22-DeepRL/README.md",
        "summary": "Agent-environment loops, Q-Learning, and Policy Gradient methods.",
        "keywords": "Path: 22-deeprl.md",
        "path": "22-deeprl.md"
      },
      {
        "name": "Multi-Agent Systems",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/6-Other/23-MultiagentSystems/README.md",
        "summary": "Decentralized agents, coordination, negotiation, and emergent behaviors.",
        "keywords": "Path: 23-multiagentsystems.md",
        "path": "23-multiagentsystems.md"
      }
    ]
  },
  {
    "id": 7,
    "name": "AI Ethics",
    "desc": "Responsible AI principles and fairness considerations.",
    "status": "complete",
    "lessons": [
      {
        "name": "AI Ethics and Responsible AI",
        "status": "complete",
        "type": "Learn",
        "lang": "\u2014",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/7-Ethics/README.md",
        "summary": "Fairness, privacy, security, transparency, and accountability in AI.",
        "keywords": "Path: 24-ethics.md",
        "path": "24-ethics.md"
      }
    ]
  },
  {
    "id": 8,
    "name": "Extras",
    "desc": "Multi-modal networks, CLIP, and VQGAN models.",
    "status": "complete",
    "lessons": [
      {
        "name": "Multi-Modal Networks, CLIP and VQGAN",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/microsoft/AI-For-Beginners/tree/main/lessons/X-Extras/X1-MultiModal/README.md",
        "summary": "Learn about multi-modal models combining text and images, such as CLIP and generative VQGAN.",
        "keywords": "Path: 25-multimodal.md",
        "path": "25-multimodal.md"
      }
    ]
  }
];
