// Auto-generated by scrape_madewithml.py — do not edit manually.
export const MADE_WITH_ML_PHASES = [
  {
    "id": 0,
    "name": "Design",
    "desc": "Set up project requirements, environments, and core ML system design.",
    "status": "complete",
    "lessons": [
      {
        "name": "Setup",
        "status": "complete",
        "type": "Build",
        "lang": "Python, Bash",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Setting up our development environment for local and Anyscale development.",
        "keywords": "Path: 01-setup.md",
        "path": "01-setup.md"
      },
      {
        "name": "Product Design",
        "status": "complete",
        "type": "Learn",
        "lang": "\u2014",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Designing our machine learning application from product requirements.",
        "keywords": "Path: 02-product.md",
        "path": "02-product.md"
      },
      {
        "name": "Systems Design",
        "status": "complete",
        "type": "Learn",
        "lang": "\u2014",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Designing the architecture and infrastructure for our ML application.",
        "keywords": "Path: 03-systems.md",
        "path": "03-systems.md"
      }
    ]
  },
  {
    "id": 1,
    "name": "Data",
    "desc": "Ingestion, exploratory data analysis, data splitting, and pre-processing.",
    "status": "complete",
    "lessons": [
      {
        "name": "Data Preparation",
        "status": "complete",
        "type": "Build",
        "lang": "Python, SQL",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Loading, cleaning and deterministically splitting our datasets.",
        "keywords": "Path: 04-preparation.md",
        "path": "04-preparation.md"
      },
      {
        "name": "Exploratory Data Analysis",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Exploring distributions, schemas, and cleaning text data.",
        "keywords": "Path: 05-exploration.md",
        "path": "05-exploration.md"
      },
      {
        "name": "Data Preprocessing",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Tokenizing, encoding labels, and parsing text datasets.",
        "keywords": "Path: 06-preprocessing.md",
        "path": "06-preprocessing.md"
      },
      {
        "name": "Distributed Data",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Scaling dataset operations using distributed Ray Data.",
        "keywords": "Path: 07-distributed.md",
        "path": "07-distributed.md"
      }
    ]
  },
  {
    "id": 2,
    "name": "Model",
    "desc": "Define model, optimize parameters, train pipelines, and evaluate metrics.",
    "status": "complete",
    "lessons": [
      {
        "name": "Model Training",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Creating neural architectures, custom training loops, and configurations.",
        "keywords": "Path: 08-training.md",
        "path": "08-training.md"
      },
      {
        "name": "Experiment Tracking",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Tracking training metrics and versioning model runs with MLflow.",
        "keywords": "Path: 09-tracking.md",
        "path": "09-tracking.md"
      },
      {
        "name": "Hyperparameter Tuning",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Running parameter sweeps and search optimization with Ray Tune.",
        "keywords": "Path: 10-tuning.md",
        "path": "10-tuning.md"
      },
      {
        "name": "Model Evaluation",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Analyzing performance, computing slicing metrics and slice evaluations.",
        "keywords": "Path: 11-evaluation.md",
        "path": "11-evaluation.md"
      },
      {
        "name": "Model Serving",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Exposing endpoints for offline batch and real-time online serving using Ray Serve.",
        "keywords": "Path: 12-serving.md",
        "path": "12-serving.md"
      }
    ]
  },
  {
    "id": 3,
    "name": "Develop",
    "desc": "Code structure, refactoring, and scripting best practices.",
    "status": "complete",
    "lessons": [
      {
        "name": "Python Scripting",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Refactoring notebook code into modular, production-ready Python scripts.",
        "keywords": "Path: 13-scripting.md",
        "path": "13-scripting.md"
      },
      {
        "name": "Command-line (CLI)",
        "status": "complete",
        "type": "Build",
        "lang": "Python, Bash",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Exposing scripting workflows using argument parsers and bash command interfaces.",
        "keywords": "Path: 14-cli.md",
        "path": "14-cli.md"
      }
    ]
  },
  {
    "id": 4,
    "name": "Utilities",
    "desc": "Logging, documentation, styling, and pre-commit automation.",
    "status": "complete",
    "lessons": [
      {
        "name": "Logging",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Adding structured runtime logging to python execution pipelines.",
        "keywords": "Path: 15-logging.md",
        "path": "15-logging.md"
      },
      {
        "name": "Documentation",
        "status": "complete",
        "type": "Build",
        "lang": "Python, Markdown",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Auto-generating source code documentation websites using MkDocs.",
        "keywords": "Path: 16-documentation.md",
        "path": "16-documentation.md"
      },
      {
        "name": "Code Styling",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Formatting and linting python scripts using Black and Flake8 styling rules.",
        "keywords": "Path: 17-styling.md",
        "path": "17-styling.md"
      },
      {
        "name": "Pre-commit Hooks",
        "status": "complete",
        "type": "Build",
        "lang": "YAML, Bash",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Automating styling and test checks prior to code commits using git hooks.",
        "keywords": "Path: 18-pre-commit.md",
        "path": "18-pre-commit.md"
      }
    ]
  },
  {
    "id": 5,
    "name": "Test",
    "desc": "Testing code logic, data distributions, and model performance.",
    "status": "complete",
    "lessons": [
      {
        "name": "Code Testing",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML",
        "summary": "Unit and integration testing of code logic using pytest.",
        "keywords": "Path: 19-test-code.md",
        "path": "19-test-code.md"
      },
      {
        "name": "Data Testing",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML",
        "summary": "Testing dataset expectations, schemas and drift anomalies.",
        "keywords": "Path: 20-test-data.md",
        "path": "20-test-data.md"
      },
      {
        "name": "Model Testing",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML",
        "summary": "Behavioral testing, invariance tests, and minimum functionality checks on model artifacts.",
        "keywords": "Path: 21-test-models.md",
        "path": "21-test-models.md"
      }
    ]
  },
  {
    "id": 6,
    "name": "Reproducibility",
    "desc": "Data, model, and code version control.",
    "status": "complete",
    "lessons": [
      {
        "name": "Data & Model Versioning",
        "status": "complete",
        "type": "Build",
        "lang": "Python, Git",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Versioning inputs, weights, and results for exact model reproducibility.",
        "keywords": "Path: 22-versioning.md",
        "path": "22-versioning.md"
      }
    ]
  },
  {
    "id": 7,
    "name": "Production",
    "desc": "Scaling workloads, CI/CD pipelines, and active performance monitoring.",
    "status": "complete",
    "lessons": [
      {
        "name": "Jobs & Services",
        "status": "complete",
        "type": "Build",
        "lang": "YAML, Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Defining scalable cloud workloads and deploying microservices using Anyscale.",
        "keywords": "Path: 23-jobs-services.md",
        "path": "23-jobs-services.md"
      },
      {
        "name": "CI/CD Workflows",
        "status": "complete",
        "type": "Build",
        "lang": "YAML, Bash",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Automating continuous training and deployment pipelines via GitHub Actions.",
        "keywords": "Path: 24-cicd.md",
        "path": "24-cicd.md"
      },
      {
        "name": "System Monitoring",
        "status": "complete",
        "type": "Build",
        "lang": "Python",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Monitoring model predictions, inputs, and drift alerts post-deployment.",
        "keywords": "Path: 25-monitoring.md",
        "path": "25-monitoring.md"
      },
      {
        "name": "Data Engineering",
        "status": "complete",
        "type": "Build",
        "lang": "Python, SQL",
        "url": "https://github.com/GokuMohandas/Made-With-ML/blob/main/notebooks/madewithml.ipynb",
        "summary": "Building automated ETL data pipelines and database synchronization workflows.",
        "keywords": "Path: 26-data-engineering.md",
        "path": "26-data-engineering.md"
      }
    ]
  }
];
